services:
  game:
    mem_limit: 350m
    cpus: "0.35"
    build:
      context: .
      dockerfile: ./cmd/game/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    environment:
      - REDIS_MATCHMAKE_ADDR=redis-matchmaking:6379
      - REDIS_GAMEPLAY_ADDR=redis-gameplay:6379
      - ENV=${ENV}
    depends_on:
      - redis-matchmaking
      # - redis-gameplay
    restart: unless-stopped

  auth:
    mem_limit: 64m
    cpus: "0.05"
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    ports:
      - "8080:8080"
    environment:
      - AUTH_PORT=8080
      - JWT_SECRET=sadie-dog-poop-poop-poop
      - REDIS_MATCHMAKE_ADDR=redis-matchmaking:6379
      - REDIS_GAMEPLAY_ADDR=redis-gameplay:6379
      - ENV=${ENV}
    depends_on:
      - redis-matchmaking
      # - redis-gameplay
    restart: unless-stopped
    
  ws-gateway:
    mem_limit: 200m
    cpus: "0.20"
    build:
      context: .
      dockerfile: ./cmd/wsgateway/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    ports:
      - "8089:8089"
    environment:
      - WEBSOCKET_PORT=8089
      - JWT_SECRET=sadie-dog-poop-poop-poop
      - REDIS_MATCHMAKE_ADDR=redis-matchmaking:6379
      - REDIS_GAMEPLAY_ADDR=redis-gameplay:6379
      - ENV=${ENV}
    depends_on:
      - redis-matchmaking
      # - redis-gameplay
    restart: unless-stopped
  
  janitor:
    mem_limit: 64m
    cpus: "0.05"
    build:
      context: .
      dockerfile: ./cmd/janitor/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    environment:
      - REDIS_MATCHMAKE_ADDR=redis-matchmaking:6379
      - REDIS_GAMEPLAY_ADDR=redis-gameplay:6379
      - ENV=${ENV}
    depends_on:
      - redis-matchmaking
      # - redis-gameplay
    restart: unless-stopped
    
    
  matchmake:
    mem_limit: 100m
    cpus: "0.10"
    build:
      context: .
      dockerfile: ./cmd/matchmake/Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    environment:
      - REDIS_MATCHMAKE_ADDR=redis-matchmaking:6379
      - ENV=${ENV}
    depends_on:
      - redis-matchmaking
    restart: unless-stopped
  
  redis-matchmaking:
    mem_limit: 256m
    cpus: "0.20"
    image: redis/redis-stack
    ports:
      - "6380:6379" # external port:container port (optional, useful for debugging/analytics)
    restart: unless-stopped

#   redis-gameplay:
#     image: redis/redis-stack
#     ports:
#       - "6381:6379" # maybe remove, optional (useful for debugging/analytics)
#     volumes:
#       - gameplay_data:/data
#     restart: unless-stopped
  
# volumes:
#   gameplay_data:
