# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis/redis-stack:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set environment variables
      run: |
        echo "ENV=PROD" >> $GITHUB_ENV
        echo "PORT=8083" >> $GITHUB_ENV
        echo "REDIS_ADDR=localhost:6379" >> $GITHUB_ENV

    - name: Run Go tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

